// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gxygwnokekzwulebgkli.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd4eWd3bm9rZWt6d3VsZWJna2xpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg1MTIyMDQsImV4cCI6MjA3NDA4ODIwNH0.ClbezN6NtvCFAa0LRfiLNDBrFVKc1y1L-uKq6rWlnXY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});